### ISSUE TITLE
Maximum stack depth has been reached

### ISSUE THREAD

**Issue by novumcoder** [Forceea/Forceea-data-factory#201]
### Summary

I simply want to delete everything asynchronously but get the batch limit error. Don't know why. See screenshot and code attached.

### Reproduction
see attached ZIP file with my Helper class, and check deleteRecords method. That one fails with the error you see on the screenshot. I see it runs too many batches, but i cant limit it. Whats the proper way of limiting it or is this a bug?

### Workaround
none

![image](https://user-images.githubusercontent.com/6917790/165932331-76756a9b-af59-4ede-97c3-3895ca5e038e.png)
[Helper.zip](https://github.com/Forceea/Forceea-data-factory/files/8590273/Helper.zip)

**Comment by nmitrakis** [comment]
You use a Developer org. In Developer orgs there is a limit of 5 Queueable Apex jobs that can be chained (this is a Salesforce limitation). Use a sandbox instead.

From the screenshot I see that you're trying to delete many SObjects, which is fine.

**Comment by novumcoder** [comment]
Ok but isn't it possible to limit it in a way so it also works with the limits on the dev org? Currently i have a dev org only to prepare for a demo. :-D @nmitrakis

**Comment by nmitrakis** [comment]
You can make it work for a Dev org under the following assumptions:
- You have up to 5 FObjects in your Template
- Every SObject has less than 9500 records to delete (or less, based on various governor limits that Forceea will consider).

**Comment by nmitrakis** [comment]
Another alternative would be to create a Scratch Enterprise org.

**Comment by novumcoder** [comment]
ok thanks @nmitrakis

**Comment by nmitrakis** [comment]
Some notes in regards to your Helper class:
- Use the `Forceea.Template` class instead of the old `Map<String, FObject>` for Templates. The Forceea.Template is much more powerful, since it internally provides the Map along with many methods for Template management.
- Avoid `setRequiredFields(true)`. It's good for an initial investigation of required fields, but you don't have the control over the definitions. It's always a best practice to explicitly define all required fields.
- For dynamic dates you can use variables, for example for min/max values for a random date, e.g.
```
    .setVariable('minDate', Date.today().addDays(-30)
    .setVariable('maxDate', Date.today().addDays(30)
    .setDefinition(MyObject__c.MyDate__c, 'random type(date) from({@minDate}) to({@maxDate})
```
- When creating records asynchronously use smaller number of days for each FObject (using setNumberOfRecords). Consider these numbers as proportions: for 100 accounts create 100 contacts, 100 cases, 200 contracts, etc. If theses number are smaller (e.g 10 instead of 100) Forceea will generally make a better decision for the optimized number of iterations that can be executed per transaction.
- Use constants for every FObject key value
