### ISSUE TITLE
Deploy to SF button doesn't work

### ISSUE THREAD

**Issue by aocole** [Forceea/Forceea-data-factory#82]
**Describe the bug**
When using the Deploy to Salesforce button, an oauth error is produced, and the app is not deployed

**To Reproduce**

1. Go to https://github.com/nmitrakis/Forceea
2. Click on Deploy to Salesforce
3. Click on Login to Salesforce
4. See oauth error

**Expected behavior**
Should have deployed

**Screenshots**
<img width="562" alt="screen shot 2018-12-07 at 11 51 47 am" src="https://user-images.githubusercontent.com/393591/49669549-8442e080-fa16-11e8-9870-da75eb9f31e5.png">

**Additional context**

**Comment by nmitrakis** [comment]
Andrew, this utility is an external tool created by Andrew Fawcett (https://andyinthecloud.com/category/githubsfdeploy). This issue seems to exist not only on Forceea repo, but in other repos as well (e.g. https://github.com/financialforcedev/apex-mdapi) and it depends on the org to be installed.

The utility has failed to deploy to a new Developer org, which looks like a bug. Unfortunately we have no control over this Heroku utility and I can't identify the problem that generates the failure.

If you use a Developer org to test Forceea, please try another org. I've tried several orgs (mainly Developer); some work, some don't.

**Comment by aocole** [comment]
OK. Thanks for your response.

**Comment by nmitrakis** [comment]
One solution could be to create an unmanaged package for distribution. Even though it has its limitation, it's a solution that could be easily used for evaluation purposes. I'll see this in the near future.
The best alternative solution is to use Salesforce CLI (or ant) to deploy the metadata to any org. The manual has details about this.

**Comment by nmitrakis** [comment]
Please install the unmanaged package
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t580000003QlE.
This will allow you to deploy the framework without any issue.
